services:
  mysql:
    container_name: mysql
    image: mysql
    environment:
      MYSQL_USER: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    restart: unless-stopped
    volumes:
      - my-db:/var/lib/mysql
    ports:
      - '3306:3306'
    expose:
      - '3306'

  backend:
    container_name: backend
    image: wassimhl1920/achat
    ports:
      - '8089:8089'
    depends_on:
      - mysql
volumes:
  my-db:
    driver: local